// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPwTgTqzAkms9jpNbgBkwY7OgjB-6R8dY',
    appId: '1:635633140714:web:e915d9a3850f670e596893',
    messagingSenderId: '635633140714',
    projectId: 'store-app-d3b10',
    authDomain: 'store-app-d3b10.firebaseapp.com',
    storageBucket: 'store-app-d3b10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFHrZ9jYnXmLAq7tpXRiIEoKLhBjAN8Z0',
    appId: '1:635633140714:android:b607521c667a0edb596893',
    messagingSenderId: '635633140714',
    projectId: 'store-app-d3b10',
    storageBucket: 'store-app-d3b10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIIpjt-6Ru4kMwSoereuFnxvwBlU4KqqA',
    appId: '1:635633140714:ios:8637cb846124bf81596893',
    messagingSenderId: '635633140714',
    projectId: 'store-app-d3b10',
    storageBucket: 'store-app-d3b10.appspot.com',
    iosClientId: '635633140714-vu05o9p2av0igmqf7hjq0hmpa0qci1i6.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeApp',
  );
}
